name: Run e2e Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run e2e Tests
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: bitnami/postgresql:latest
        ports:
          - "5432:5432"
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test:e2e
        env:
          JWT_SECRET: teste-secret
          DATABASE_URL: "postgres://docker:docker@localhost:5432/apisolid"
